#!/bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

flavor=${1:-bar}

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT

#clock -sf 'S%a %H:%M' > "$PANEL_FIFO" &
PANEL_MULTI_MONITOR=$(xrandr | grep -c  "\bconnected\b")
#if [ $PANEL_MULTI_MONITOR -gt 0 ] ; then
#  echo "PANEL_MULTI_MONITOR: $PANEL_MULTI_MONITOR"
#  bspc-status.sh > "$PANEL_FIFO" &
#  xtitle -sf 'T%{S+}%s%{S}' > "$PANEL_FIFO" &
#  acpisecondary.sh > "$PANEL_FIFO" &
#else
  bspc control --subscribe > "$PANEL_FIFO" &
  xtitle -sf 'T%s' > "$PANEL_FIFO" &
  panel_right.sh > "$PANEL_FIFO" &
#fi

. panel_colors

case "$flavor" in
	bar)
		#FONT_FAMILY='-*-terminus-medium-r-normal-*-12-*-*-*-c-*-*-1'
    cat "$PANEL_FIFO" | panel_bar | bar -g x$PANEL_HEIGHT -f "$FONT_FAMILY" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &
    #cat "$PANEL_FIFO" | bar -g x$PANEL_HEIGHT -f "$FONT_FAMILY" -F "white" -B "black"
    #if [ $(xrandr | grep -c VGA1\ connected) -gt 1 ] ; then
      #cat "$PANEL_FIFO" | panel_bar | bar -g ${PANEL_SECONDARY_WIDTH}x$PANEL_HEIGHT -f "$FONT_FAMILY" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &
    #fi
		;;
	dzen2)
		FONT_FAMILY='DejaVu Sans'
		FONT_SIZE=11
		cat "$PANEL_FIFO" | panel_dzen2 -f "$FONT_FAMILY" -s "$FONT_SIZE" | dzen2 -h $PANEL_HEIGHT -dock -ta l -title-name panel -fn "${FONT_FAMILY}:pixelsize=${FONT_SIZE}" -fg "$COLOR_FOREGROUND" -bg "$COLOR_BACKGROUND" &
		;;
esac

wait
